graph TD
    ProjeLideri["Furkan Zihni Özen - Proje Lideri"]
    
    TestLideri["Ayçin Kapar - Test Lideri<br/><small>• Test stratejilerinin belirlenmesi<br/>• Test otomasyonu ve kalite kontrol<br/>• Hata yönetimi ve raporlama</small>"]
    
    TestUzmani["Ahmet Kürşat Dişbudak - Test Uzmanı<br/><small>• Yazılım test uzmanlığı<br/>• Test senaryoları oluşturma<br/>• Hata raporlama</small>"]
    
    ProjeLideri --> TestLideri
    TestLideri --> TestUzmani